version: '3.8'
services:
  kugou-sync:
    image: sixiang16123/kugou-sync:latest   # 替换为你的镜像地址
    container_name: kugou-sync
    restart: always
    ports:
      - "5000:5000"            # 左边是飞牛主机端口，可改成别的，右边保持 5000
    environment:
      - KUGOU_COOKIE=你的cookie完整字符串
      - INTERVAL_MIN=60        # 定时同步间隔（分钟）
      - WEB_PORT=5000          # 保持与 ports 右边一致
    volumes:
      - /volume1/music:/music  # 左边改成你 NAS 上的真实音乐存放路径
