services:
  kugou-sync:
    image: sixiang16123/kugou-sync:latest
    container_name: kugou-sync
    restart: always
    ports:
      - "5000:5000"
    environment:
      - KUGOU_COOKIE=你的完整cookie字符串（用于获取下载链接时参考kg_mid，可选）
      - INTERVAL_MIN=60
      - WEB_PORT=5000
    volumes:
      - /volume1/music:/music          # 下载路径
      - /vol1/1000/docker/kugou-sync/data:/app/data   # 保存歌单配置
